# Generated by Django 5.2.6 on 2025-09-22 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('picked_up', 'Picked Up from Warehouse'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('exception', 'Delivery Exception'), ('returned', 'Returned to Sender')], max_length=20)),
                ('event_date', models.DateTimeField(help_text='When this delivery event occurred')),
                ('location', models.CharField(blank=True, help_text='Location where event occurred', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
                ('carrier_reference', models.CharField(blank=True, help_text="Carrier's reference for this event", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Event',
                'verbose_name_plural': 'Delivery Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_attempted_at',
            field=models.DateTimeField(blank=True, help_text='When delivery was first attempted', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmation_method',
            field=models.CharField(blank=True, choices=[('signature', 'Signature Required'), ('photo', 'Photo Confirmation'), ('contactless', 'Contactless Delivery'), ('mailbox', 'Mailbox Delivery'), ('front_door', 'Front Door'), ('other', 'Other')], help_text='How delivery was confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions from customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_free_shipping',
            field=models.BooleanField(default=False, help_text='Whether this order qualified for free shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, help_text='When order went out for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, default='Standard Carrier', help_text='Shipping carrier/company', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_duration',
            field=models.CharField(blank=True, help_text="Expected shipping duration (e.g., '5-7 business days')", max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_display',
            field=models.CharField(default='Standard Shipping', help_text='Display name for shipping method', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date calculated at checkout', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('overnight', 'Overnight Shipping')], default='standard', help_text='Selected shipping method type', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_method'], name='Order_order_shippin_e42937_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estimated_delivery_date'], name='Order_order_estimat_0e2062_idx'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='Order.order'),
        ),
    ]
